### ISSUE TITLE
Speckle Manager:

### ISSUE THREAD

**Issue by daviddekoning** [speckleworks/SpeckleInstaller#15]
[issue created from @didimitrie's note]

Allow for piecemeal installation and updating of the various parts of speckle, so as to be able to push updates and bug fixes to end-users faster, on a "same-day" approach. Can be coupled with an account manager (so that users have a single point where they can add/remove/edit accounts). 

Time required: two weeks(ish) full time. 

Preliminary architecture/pieces: 
- [x] electron app w/h vue ui (team skills cross-over) 
- [x] installation view 
- [x] accounts view (not a priority)
- [x] CI for all speckle pieces (rhino, grasshopper, dynamo, revit, core geometry, elements) 

Would retire the old monolithic [SpeckleInstaller](https://github.com/speckleworks/SpeckleInstaller). 

@mishaelnuh start this up next to documentation; thereafter handed over to @didimitrie and/or @teocomi

**Comment by daviddekoning** [comment]
How about (for a first step) adding individual client installers alongside the monolithic one? That way users can take individual updates, or update the whole thing.

Are there off-the-shelf install managers that we could point at a list of individual installers?

**Comment by teocomi** [comment]
I think we can close this one and move further issues to the SpeckleManager repo.
