### ISSUE TITLE
Installer adds itself to Windows startup without warning

### ISSUE THREAD

**Issue by radumg** [speckleworks/SpeckleInstaller#5]
re-started my computer for the first time since i installed using the `SpeckleInstaller` and got this beauty taking up half the screen when Windows started.

![image](https://user-images.githubusercontent.com/11439624/49284391-63b1de00-f48c-11e8-9b0b-751c9a85663c.png)

Checked `Startup` in `Task Manager` and Speckle had indeed added itself to it - but there was never any indication it would do so or an option. It's also non-dismissable and takes a while....

![image](https://user-images.githubusercontent.com/11439624/49284544-cd31ec80-f48c-11e8-8477-78a81de23d39.png)

I think we need to re-think that behaviour  - it's the quickest way to start hating on an app, we don't want Speckle to end up next to the top offenders (`Creative Cloud`, `Autodesk Desktop App` and other incessant zombie apps that just keep coming back).

**Comment by teocomi** [comment]
Added check box during installation.

Re the fact that it takes half of your screen, what resolution are you using @radumg ?? The window was 300x300...

**Comment by radumg** [comment]
Maybe half the screen was an exaggeration, but it was sizeable.
Using 4K screen so 3840 x 2160 (with 200% scaling I think)
