### ISSUE TITLE
Installer is not dismissable

### ISSUE THREAD

**Issue by radumg** [speckleworks/SpeckleInstaller#6]
## Currently

Installer pops up and there is now (easy) way for the user to cancel or quit it.
You can off course kill of the process in Task Manager, but that's not exactly user friendly.

Wouldn't be such an issue if it was quick, but it's not, hangs there for 30s.

## Proposed

There should be a `Cancel` button or a standard `X` close button in top-right of window that immediately closes the app, regardless of whether it finished checking or not.

**Comment by teocomi** [comment]
Why would you *not* want a new Speckle?
Btw gotcha, we'll add that!

**Comment by radumg** [comment]
added something in PR #7 , take a look @teocomi ? (and be gentle... 🙈 )
